# Generated by Django 2.0.3 on 2018-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='A short description of the location.', null=True)),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
    ]
