# Generated by Django 2.0.3 on 2018-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='No author', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
